window.REPORT_DATA = {
  "totalDays": 100,
  "elapsed": "5.12",
  "totalFactions": 18,
  "totalNPCs": 152,
  "generatedAt": "2026/5/30 19:02:25",
  "summary": {
    "aliveFactions": 18,
    "aliveNPCs": 152,
    "breakthroughSuccess": 0,
    "breakthroughFail": 0,
    "totalDeaths": 0,
    "avgQi": 445.36,
    "attacks": 0,
    "alliances": 8,
    "companionPairs": 16,
    "totalBirths": 1,
    "genderMale": 107,
    "genderFemale": 45
  },
  "timeline": [
    {
      "day": 50,
      "aliveNPC": 151,
      "deadNPC": 0,
      "aliveFaction": 18,
      "avgQi": 219.88,
      "maxQi": 1700,
      "avgProgress": 0.1502,
      "avgStone": 14219,
      "avgDisciples": 334,
      "breakthroughs": 0,
      "deaths": 0
    },
    {
      "day": 100,
      "aliveNPC": 152,
      "deadNPC": 0,
      "aliveFaction": 18,
      "avgQi": 445.36,
      "maxQi": 3400,
      "avgProgress": 0.1541,
      "avgStone": 13145,
      "avgDisciples": 402,
      "breakthroughs": 0,
      "deaths": 0
    }
  ],
  "factions": [
    {
      "id": "sect_001",
      "name": "青云宗",
      "isNeutral": false,
      "destroyed": false,
      "initStone": 5000,
      "finalStone": 3564,
      "initDisc": 500,
      "finalDisc": 599,
      "initFood": 3000,
      "finalFood": 128674,
      "stability": 105,
      "territory": 914
    },
    {
      "id": "sect_002",
      "name": "天剑宗",
      "isNeutral": false,
      "destroyed": false,
      "initStone": 3000,
      "finalStone": 1115,
      "initDisc": 200,
      "finalDisc": 301,
      "initFood": 1500,
      "finalFood": 126670,
      "stability": 105,
      "territory": 889
    },
    {
      "id": "sect_003",
      "name": "玄真观",
      "isNeutral": false,
      "destroyed": false,
      "initStone": 4000,
      "finalStone": 3962,
      "initDisc": 300,
      "finalDisc": 405,
      "initFood": 2500,
      "finalFood": 125882,
      "stability": 105,
      "territory": 892
    },
    {
      "id": "sect_004",
      "name": "血煞门",
      "isNeutral": false,
      "destroyed": false,
      "initStone": 3500,
      "finalStone": 35842,
      "initDisc": 350,
      "finalDisc": 647,
      "initFood": 1800,
      "finalFood": 131678,
      "stability": 80,
      "territory": 882
    },
    {
      "id": "sect_005",
      "name": "幽冥教",
      "isNeutral": false,
      "destroyed": false,
      "initStone": 2800,
      "finalStone": 3069,
      "initDisc": 250,
      "finalDisc": 349,
      "initFood": 1200,
      "finalFood": 109945,
      "stability": 105,
      "territory": 794
    },
    {
      "id": "sect_006",
      "name": "毒蝎帮",
      "isNeutral": false,
      "destroyed": false,
      "initStone": 800,
      "finalStone": 3068,
      "initDisc": 100,
      "finalDisc": 205,
      "initFood": 600,
      "finalFood": 97012,
      "stability": 105,
      "territory": 706
    },
    {
      "id": "sect_007",
      "name": "药王谷",
      "isNeutral": false,
      "destroyed": false,
      "initStone": 2000,
      "finalStone": 961,
      "initDisc": 200,
      "finalDisc": 317,
      "initFood": 1000,
      "finalFood": 25065,
      "stability": 105,
      "territory": 217
    },
    {
      "id": "sect_008",
      "name": "天机阁",
      "isNeutral": false,
      "destroyed": false,
      "initStone": 1500,
      "finalStone": 1015,
      "initDisc": 250,
      "finalDisc": 361,
      "initFood": 800,
      "finalFood": 29391,
      "stability": 105,
      "territory": 251
    },
    {
      "id": "sect_009",
      "name": "万妖山",
      "isNeutral": false,
      "destroyed": false,
      "initStone": 4500,
      "finalStone": 37569,
      "initDisc": 600,
      "finalDisc": 897,
      "initFood": 2000,
      "finalFood": 131789,
      "stability": 80,
      "territory": 887
    },
    {
      "id": "sect_010",
      "name": "蛮蛟族",
      "isNeutral": false,
      "destroyed": false,
      "initStone": 2000,
      "finalStone": 35253,
      "initDisc": 200,
      "finalDisc": 495,
      "initFood": 1000,
      "finalFood": 130666,
      "stability": 80,
      "territory": 876
    },
    {
      "id": "sect_011",
      "name": "大晋王朝",
      "isNeutral": false,
      "destroyed": false,
      "initStone": 1000,
      "finalStone": 3882,
      "initDisc": 800,
      "finalDisc": 905,
      "initFood": 8000,
      "finalFood": 129763,
      "stability": 105,
      "territory": 894
    },
    {
      "id": "sect_012",
      "name": "南越国",
      "isNeutral": false,
      "destroyed": false,
      "initStone": 500,
      "finalStone": 3120,
      "initDisc": 150,
      "finalDisc": 255,
      "initFood": 3000,
      "finalFood": 100105,
      "stability": 105,
      "territory": 711
    },
    {
      "id": "org_auction",
      "name": "万宝楼",
      "isNeutral": true,
      "destroyed": false,
      "initStone": 50000,
      "finalStone": 42752,
      "initDisc": 150,
      "finalDisc": 249,
      "initFood": 500,
      "finalFood": 3966,
      "stability": 105,
      "territory": 81
    },
    {
      "id": "org_escort",
      "name": "万里镖行",
      "isNeutral": true,
      "destroyed": false,
      "initStone": 8000,
      "finalStone": 812,
      "initDisc": 200,
      "finalDisc": 299,
      "initFood": 1200,
      "finalFood": 4135,
      "stability": 105,
      "territory": 80
    },
    {
      "id": "org_assassin",
      "name": "天机杀阁",
      "isNeutral": true,
      "destroyed": false,
      "initStone": 20000,
      "finalStone": 12948,
      "initDisc": 120,
      "finalDisc": 221,
      "initFood": 300,
      "finalFood": 4165,
      "stability": 105,
      "territory": 83
    },
    {
      "id": "org_bounty",
      "name": "悬赏阁",
      "isNeutral": true,
      "destroyed": false,
      "initStone": 15000,
      "finalStone": 8089,
      "initDisc": 100,
      "finalDisc": 201,
      "initFood": 400,
      "finalFood": 811,
      "stability": 105,
      "territory": 58
    },
    {
      "id": "org_market",
      "name": "百灵坊市",
      "isNeutral": true,
      "destroyed": false,
      "initStone": 30000,
      "finalStone": 34036,
      "initDisc": 180,
      "finalDisc": 279,
      "initFood": 600,
      "finalFood": 2508,
      "stability": 105,
      "territory": 72
    },
    {
      "id": "org_intelligence",
      "name": "妙音阁",
      "isNeutral": true,
      "destroyed": false,
      "initStone": 12000,
      "finalStone": 5553,
      "initDisc": 160,
      "finalDisc": 259,
      "initFood": 500,
      "finalFood": 3429,
      "stability": 105,
      "territory": 79
    }
  ],
  "factionActions": [
    {
      "name": "加强防御",
      "count": 1436
    },
    {
      "name": "内部发展",
      "count": 326
    },
    {
      "name": "布置护山大阵",
      "count": 27
    },
    {
      "name": "外交结盟",
      "count": 8
    },
    {
      "name": "贸易交换",
      "count": 3
    }
  ],
  "npcActions": [
    {
      "name": "修炼",
      "count": 11410
    },
    {
      "name": "空闲",
      "count": 3427
    },
    {
      "name": "夺取掌门之位",
      "count": 156
    },
    {
      "name": "执行任务",
      "count": 82
    },
    {
      "name": "挑战上位",
      "count": 15
    },
    {
      "name": "接取任务",
      "count": 10
    },
    {
      "name": "赴修炼场修炼",
      "count": 8
    },
    {
      "name": "交付任务",
      "count": 2
    }
  ],
  "goap": {
    "factionOk": 357,
    "factionFb": 1443,
    "npcOk": 170,
    "npcFb": 13741
  },
  "npcRoster": [
    {
      "factionId": "sect_001",
      "factionName": "青云宗",
      "members": [
        {
          "name": "清玄真人",
          "rankName": "元婴",
          "role": "leader",
          "age": 474,
          "maxAge": 1223,
          "qi": 1600,
          "progress": 0.29567822403870186,
          "stone": 200,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "明霄长老",
          "rankName": "元婴",
          "role": "elder",
          "age": 532,
          "maxAge": 1484,
          "qi": 1360,
          "progress": 0.10577612318558795,
          "stone": 80,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "守一长老",
          "rankName": "金丹",
          "role": "elder",
          "age": 211,
          "maxAge": 608,
          "qi": 760,
          "progress": 0.13743928565265345,
          "stone": 80,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "洛青长老",
          "rankName": "金丹",
          "role": "elder",
          "age": 240,
          "maxAge": 658,
          "qi": 760,
          "progress": 0.2978544287491684,
          "stone": 80,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "云衡子",
          "rankName": "金丹",
          "role": "heir",
          "age": 311,
          "maxAge": 512,
          "qi": 720,
          "progress": 0.06578097769492625,
          "stone": 60,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "陆行舟",
          "rankName": "金丹",
          "role": "outer_disciple",
          "age": 216,
          "maxAge": 514,
          "qi": 604,
          "progress": 0.04090911026685977,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "谢无咎",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 140,
          "maxAge": 262,
          "qi": 456,
          "progress": 0.02643670004526007,
          "stone": 0,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "沈砚",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 115,
          "maxAge": 230,
          "qi": 304,
          "progress": 0.19442175825443675,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "顾清岚",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 158,
          "maxAge": 249,
          "qi": 304,
          "progress": 0.15956184346303437,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "林照夜",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 155,
          "maxAge": 265,
          "qi": 304,
          "progress": 0.014104548852027967,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "韩知微",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 98,
          "maxAge": 212,
          "qi": 304,
          "progress": 0.23604310464323572,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "叶扶摇",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 80,
          "maxAge": 226,
          "qi": 304,
          "progress": 0.18117757234125814,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "白景行",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 91,
          "maxAge": 200,
          "qi": 152,
          "progress": 0.2993551083582811,
          "stone": 24,
          "contribution": 10,
          "quests": 1,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "秦若水",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 67,
          "maxAge": 103,
          "qi": 136.39999999999998,
          "progress": 0.2876991119341273,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": "npc_128",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "苏问心",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 50,
          "maxAge": 110,
          "qi": 124,
          "progress": 0.14208534092942104,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "唐归云",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 38,
          "maxAge": 114,
          "qi": 124,
          "progress": 0.02979540345346282,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        }
      ]
    },
    {
      "factionId": "sect_002",
      "factionName": "天剑宗",
      "members": [
        {
          "name": "剑痴",
          "rankName": "元婴",
          "role": "leader",
          "age": 714,
          "maxAge": 1142,
          "qi": 1600,
          "progress": 0.13852264394511937,
          "stone": 200,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "藏锋长老",
          "rankName": "金丹",
          "role": "elder",
          "age": 265,
          "maxAge": 565,
          "qi": 760,
          "progress": 0.0749503752356532,
          "stone": 80,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "断岳长老",
          "rankName": "金丹",
          "role": "elder",
          "age": 269,
          "maxAge": 636,
          "qi": 760,
          "progress": 0.21081036739871128,
          "stone": 80,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "剑鸣",
          "rankName": "金丹",
          "role": "heir",
          "age": 368,
          "maxAge": 609,
          "qi": 720,
          "progress": 0.1497887793029257,
          "stone": 60,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "沈孤剑",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 141,
          "maxAge": 274,
          "qi": 334.4,
          "progress": 0.09712194277895769,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": "npc_032",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "赵寒星",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 66,
          "maxAge": 219,
          "qi": 304,
          "progress": 0.17045862323764052,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "柳穿云",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 85,
          "maxAge": 278,
          "qi": 152,
          "progress": 0.2999052976459238,
          "stone": 4,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": "npc_031",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "陆惊鸿",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 35,
          "maxAge": 115,
          "qi": 136.39999999999998,
          "progress": 0.24475379952009502,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": "npc_111",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "姜听雪",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 67,
          "maxAge": 108,
          "qi": 124,
          "progress": 0.13332232112294462,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "方不弃",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 54,
          "maxAge": 107,
          "qi": 124,
          "progress": 0.06738827370712945,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        }
      ]
    },
    {
      "factionId": "sect_003",
      "factionName": "玄真观",
      "members": [
        {
          "name": "无尘道人",
          "rankName": "元婴",
          "role": "leader",
          "age": 772,
          "maxAge": 1129,
          "qi": 1600,
          "progress": 0.3000543491217183,
          "stone": 200,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "静玄长老",
          "rankName": "金丹",
          "role": "elder",
          "age": 222,
          "maxAge": 513,
          "qi": 760,
          "progress": 0.25279449755086086,
          "stone": 80,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "知白长老",
          "rankName": "金丹",
          "role": "elder",
          "age": 451,
          "maxAge": 698,
          "qi": 760,
          "progress": 0.12076686758891328,
          "stone": 80,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "玄明子",
          "rankName": "金丹",
          "role": "heir",
          "age": 181,
          "maxAge": 503,
          "qi": 720,
          "progress": 0.09819793469794945,
          "stone": 60,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "宋守拙",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 162,
          "maxAge": 231,
          "qi": 304,
          "progress": 0.054999784613027805,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "梅听雨",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 159,
          "maxAge": 236,
          "qi": 304,
          "progress": 0.18697518158237728,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "许问玄",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 84,
          "maxAge": 222,
          "qi": 304,
          "progress": 0.11856273182264236,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "周怀素",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 46,
          "maxAge": 106,
          "qi": 136.39999999999998,
          "progress": 0.24604035202280305,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": "npc_045",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "顾云台",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 43,
          "maxAge": 107,
          "qi": 136.39999999999998,
          "progress": 0.1651126139078423,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": "npc_043",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "陈照溪",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 70,
          "maxAge": 115,
          "qi": 124,
          "progress": 0.219967003382344,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        }
      ]
    },
    {
      "factionId": "sect_004",
      "factionName": "血煞门",
      "members": [
        {
          "name": "血魔老祖",
          "rankName": "元婴",
          "role": "leader",
          "age": 461,
          "maxAge": 1020,
          "qi": 1600,
          "progress": 0.21572097809182958,
          "stone": 200,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "赤骨长老",
          "rankName": "金丹",
          "role": "elder",
          "age": 315,
          "maxAge": 576,
          "qi": 760,
          "progress": 0.22739934339469323,
          "stone": 80,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "屠山",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 103,
          "maxAge": 238,
          "qi": 304,
          "progress": 0.23826611188738028,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "黑鸦",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 77,
          "maxAge": 221,
          "qi": 304,
          "progress": 0.06157343252849003,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "血童子",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 140,
          "maxAge": 209,
          "qi": 304,
          "progress": 0.1760902424934328,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "罗刹女",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 74,
          "maxAge": 108,
          "qi": 124,
          "progress": 0.02755695527888432,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "厉无声",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 57,
          "maxAge": 100,
          "qi": 124,
          "progress": 0.29714953377800013,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "赤眉",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 34,
          "maxAge": 104,
          "qi": 124,
          "progress": 0.10706891605108651,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "血无归",
          "rankName": "金丹",
          "role": "heir",
          "age": 270,
          "maxAge": 534,
          "qi": 0,
          "progress": 0.01205015116844067,
          "stone": 180,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "饮血长老",
          "rankName": "金丹",
          "role": "elder",
          "age": 197,
          "maxAge": 555,
          "qi": 0,
          "progress": 0.2769821520207864,
          "stone": 240,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        }
      ]
    },
    {
      "factionId": "sect_005",
      "factionName": "幽冥教",
      "members": [
        {
          "name": "鬼母",
          "rankName": "元婴",
          "role": "leader",
          "age": 534,
          "maxAge": 1353,
          "qi": 1760,
          "progress": 0.07266489760449707,
          "stone": 200,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": "npc_083",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "幽姬",
          "rankName": "金丹",
          "role": "heir",
          "age": 361,
          "maxAge": 609,
          "qi": 792,
          "progress": 0.14524315717836533,
          "stone": 60,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": "npc_131",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "冥河长老",
          "rankName": "金丹",
          "role": "elder",
          "age": 245,
          "maxAge": 513,
          "qi": 760,
          "progress": 0.1655938275431417,
          "stone": 80,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "摄魂长老",
          "rankName": "金丹",
          "role": "elder",
          "age": 174,
          "maxAge": 531,
          "qi": 760,
          "progress": 0.042212292323022864,
          "stone": 80,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "阴罗",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 123,
          "maxAge": 214,
          "qi": 304,
          "progress": 0.057173203518730197,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "白骨使",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 198,
          "maxAge": 297,
          "qi": 304,
          "progress": 0.19059297102971126,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "孟千灯",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 144,
          "maxAge": 206,
          "qi": 304,
          "progress": 0.07997247738563161,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "乌啼",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 51,
          "maxAge": 103,
          "qi": 124,
          "progress": 0.011173026550266238,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "沈夜",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 78,
          "maxAge": 116,
          "qi": 124,
          "progress": 0.01894386075603649,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "鬼灯",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 75,
          "maxAge": 112,
          "qi": 124,
          "progress": 0.18288043847897484,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        }
      ]
    },
    {
      "factionId": "sect_006",
      "factionName": "毒蝎帮",
      "members": [
        {
          "name": "蝎王",
          "rankName": "金丹",
          "role": "leader",
          "age": 265,
          "maxAge": 585,
          "qi": 1000,
          "progress": 0.10281331201324083,
          "stone": 200,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "毒婆",
          "rankName": "筑基",
          "role": "elder",
          "age": 157,
          "maxAge": 283,
          "qi": 460,
          "progress": 0.24537992282316876,
          "stone": 80,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "青蝎",
          "rankName": "筑基",
          "role": "heir",
          "age": 116,
          "maxAge": 252,
          "qi": 420,
          "progress": 0.10436009301843673,
          "stone": 60,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "朱砂",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 45,
          "maxAge": 113,
          "qi": 136.39999999999998,
          "progress": 0.10498624975970505,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": "npc_069",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "灰尾",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 68,
          "maxAge": 104,
          "qi": 136.39999999999998,
          "progress": 0.1069141632339011,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": "npc_068",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "沙尾",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 47,
          "maxAge": 107,
          "qi": 124,
          "progress": 0.013678704028102864,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "黑针",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 55,
          "maxAge": 112,
          "qi": 124,
          "progress": 0.11324286380598679,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        }
      ]
    },
    {
      "factionId": "sect_007",
      "factionName": "药王谷",
      "members": [
        {
          "name": "药仙",
          "rankName": "金丹",
          "role": "leader",
          "age": 382,
          "maxAge": 620,
          "qi": 1000,
          "progress": 0.21588556383838042,
          "stone": 200,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "白芷长老",
          "rankName": "金丹",
          "role": "elder",
          "age": 207,
          "maxAge": 670,
          "qi": 836,
          "progress": 0.028588560117214012,
          "stone": 80,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": "npc_070",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "丹青子",
          "rankName": "筑基",
          "role": "heir",
          "age": 146,
          "maxAge": 229,
          "qi": 462,
          "progress": 0.21723546686540365,
          "stone": 60,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": "npc_071",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "葛洪",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 88,
          "maxAge": 238,
          "qi": 304,
          "progress": 0.2554482312909455,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "辛夷",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 36,
          "maxAge": 118,
          "qi": 136.39999999999998,
          "progress": 0.013297670160859462,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": "npc_120",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "木香",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 51,
          "maxAge": 105,
          "qi": 124,
          "progress": 0.20713636558393947,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "茯苓",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 67,
          "maxAge": 101,
          "qi": 124,
          "progress": 0.04298504164888837,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        }
      ]
    },
    {
      "factionId": "sect_008",
      "factionName": "天机阁",
      "members": [
        {
          "name": "天机老人",
          "rankName": "金丹",
          "role": "leader",
          "age": 320,
          "maxAge": 507,
          "qi": 1000,
          "progress": 0.2764497343500682,
          "stone": 200,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "玄机长老",
          "rankName": "金丹",
          "role": "elder",
          "age": 294,
          "maxAge": 585,
          "qi": 760,
          "progress": 0.032591878176428585,
          "stone": 80,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "观星子",
          "rankName": "筑基",
          "role": "heir",
          "age": 159,
          "maxAge": 245,
          "qi": 420,
          "progress": 0.17520203337070597,
          "stone": 60,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "司历",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 159,
          "maxAge": 240,
          "qi": 304,
          "progress": 0.08146584828564346,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "藏星",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 58,
          "maxAge": 118,
          "qi": 136.39999999999998,
          "progress": 0.1324702257532794,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": "npc_103",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "听潮",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 45,
          "maxAge": 109,
          "qi": 124,
          "progress": 0.23802683082243992,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "问斗",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 38,
          "maxAge": 111,
          "qi": 124,
          "progress": 0.14353261097065328,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        }
      ]
    },
    {
      "factionId": "sect_009",
      "factionName": "万妖山",
      "members": [
        {
          "name": "白泽",
          "rankName": "化神",
          "role": "leader",
          "age": 974,
          "maxAge": 2266,
          "qi": 3400,
          "progress": 0.044224753941739525,
          "stone": 200,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "青丘长老",
          "rankName": "元婴",
          "role": "elder",
          "age": 716,
          "maxAge": 1247,
          "qi": 1496,
          "progress": 0.13218187065738957,
          "stone": 80,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": "npc_005",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "玄麟",
          "rankName": "元婴",
          "role": "heir",
          "age": 668,
          "maxAge": 1309,
          "qi": 1320,
          "progress": 0.037785542234678136,
          "stone": 60,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "鹰羽长老",
          "rankName": "金丹",
          "role": "elder",
          "age": 199,
          "maxAge": 635,
          "qi": 760,
          "progress": 0.022547593498151514,
          "stone": 80,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "玄龟长老",
          "rankName": "金丹",
          "role": "elder",
          "age": 389,
          "maxAge": 612,
          "qi": 760,
          "progress": 0.2663217320545406,
          "stone": 80,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "裂山",
          "rankName": "金丹",
          "role": "outer_disciple",
          "age": 253,
          "maxAge": 689,
          "qi": 604,
          "progress": 0.15897321417019747,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "风牙",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 145,
          "maxAge": 247,
          "qi": 304,
          "progress": 0.15389658741959686,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "玉狐",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 84,
          "maxAge": 240,
          "qi": 304,
          "progress": 0.19721435300607096,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "白羽",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 87,
          "maxAge": 205,
          "qi": 304,
          "progress": 0.18464542294779743,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "黑角",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 132,
          "maxAge": 297,
          "qi": 304,
          "progress": 0.25728947148123654,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "灵角",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 134,
          "maxAge": 225,
          "qi": 304,
          "progress": 0.028497110488338476,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "青鳞",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 50,
          "maxAge": 107,
          "qi": 124,
          "progress": 0.25741833024170907,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "月牙",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 50,
          "maxAge": 103,
          "qi": 124,
          "progress": 0.08187356970278693,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "霜爪",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 77,
          "maxAge": 119,
          "qi": 124,
          "progress": 0.11265732366900419,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "赤尾",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 43,
          "maxAge": 109,
          "qi": 124,
          "progress": 0.06123068207426552,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "苍鬃",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 34,
          "maxAge": 102,
          "qi": 124,
          "progress": 0.03904425503612928,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        }
      ]
    },
    {
      "factionId": "sect_010",
      "factionName": "蛮蛟族",
      "members": [
        {
          "name": "赤煌",
          "rankName": "元婴",
          "role": "leader",
          "age": 738,
          "maxAge": 1133,
          "qi": 1600,
          "progress": 0.07332870013791039,
          "stone": 200,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "黑蛟长老",
          "rankName": "金丹",
          "role": "elder",
          "age": 324,
          "maxAge": 527,
          "qi": 760,
          "progress": 0.20251350708121887,
          "stone": 80,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "赤澜",
          "rankName": "金丹",
          "role": "heir",
          "age": 411,
          "maxAge": 623,
          "qi": 720,
          "progress": 0.2717774311788,
          "stone": 60,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "沧牙长老",
          "rankName": "筑基",
          "role": "elder",
          "age": 175,
          "maxAge": 263,
          "qi": 460,
          "progress": 0.008016779432998094,
          "stone": 80,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "雷尾",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 120,
          "maxAge": 208,
          "qi": 304,
          "progress": 0.042290069809517855,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "苍蛟",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 81,
          "maxAge": 244,
          "qi": 304,
          "progress": 0.15709911542494298,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "鳞破",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 127,
          "maxAge": 216,
          "qi": 154,
          "progress": 0.09289604843714136,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "蛮骨",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 60,
          "maxAge": 114,
          "qi": 136.39999999999998,
          "progress": 0.02263405789469083,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": "npc_081",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "赤鳞",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 44,
          "maxAge": 108,
          "qi": 124,
          "progress": 0.13188324079520405,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "江怒",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 78,
          "maxAge": 111,
          "qi": 124,
          "progress": 0.26267418987569924,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        }
      ]
    },
    {
      "factionId": "sect_011",
      "factionName": "大晋王朝",
      "members": [
        {
          "name": "国师李抱朴",
          "rankName": "金丹",
          "role": "elder",
          "age": 302,
          "maxAge": 659,
          "qi": 760,
          "progress": 0.24306301812428677,
          "stone": 80,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "太师裴玄",
          "rankName": "宗师",
          "role": "elder",
          "age": 58,
          "maxAge": 85,
          "qi": 99,
          "progress": 0.2317141196637025,
          "stone": 180,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": "npc_114",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "晋武帝",
          "rankName": "武圣",
          "role": "leader",
          "age": 40,
          "maxAge": 61,
          "qi": 90,
          "progress": 0.2849872705436866,
          "stone": 540,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "太子赵衡",
          "rankName": "宗师",
          "role": "heir",
          "age": 49,
          "maxAge": 99,
          "qi": 90,
          "progress": 0.14970710494652592,
          "stone": 120,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "丞相王肃",
          "rankName": "谋士",
          "role": "elder",
          "age": 45,
          "maxAge": 93,
          "qi": 90,
          "progress": 0.21463691228335613,
          "stone": 180,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "羽林郎陈策",
          "rankName": "弟子",
          "role": "outer_disciple",
          "age": 40,
          "maxAge": 87,
          "qi": 64,
          "progress": 0.10318638085358116,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "边军校尉",
          "rankName": "弟子",
          "role": "outer_disciple",
          "age": 44,
          "maxAge": 76,
          "qi": 64,
          "progress": 0.22050064079357118,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "禁军统领",
          "rankName": "统领",
          "role": "outer_disciple",
          "age": 24,
          "maxAge": 65,
          "qi": 37.4,
          "progress": 0.19262366511027917,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": "npc_034",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "长公主赵绾",
          "rankName": "宗师",
          "role": "outer_disciple",
          "age": 41,
          "maxAge": 97,
          "qi": 37.4,
          "progress": 0.2960776210261541,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": "npc_107",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "东宫侍卫统领",
          "rankName": "统领",
          "role": "outer_disciple",
          "age": 31,
          "maxAge": 62,
          "qi": 37.4,
          "progress": 0.29487276347140795,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": "npc_073",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "镇北将军",
          "rankName": "将军",
          "role": "outer_disciple",
          "age": 30,
          "maxAge": 78,
          "qi": 34,
          "progress": 0.14172106111108584,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "户部尚书",
          "rankName": "谋士",
          "role": "outer_disciple",
          "age": 38,
          "maxAge": 75,
          "qi": 34,
          "progress": 0.287094251268707,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "礼部尚书",
          "rankName": "谋士",
          "role": "outer_disciple",
          "age": 42,
          "maxAge": 91,
          "qi": 34,
          "progress": 0.21766570130975857,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "监天司正",
          "rankName": "谋士",
          "role": "outer_disciple",
          "age": 50,
          "maxAge": 73,
          "qi": 34,
          "progress": 0.354150020073682,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "御史秦直",
          "rankName": "谋士",
          "role": "outer_disciple",
          "age": 25,
          "maxAge": 81,
          "qi": 34,
          "progress": 0.28400784866429374,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "司农郑平",
          "rankName": "谋士",
          "role": "outer_disciple",
          "age": 35,
          "maxAge": 70,
          "qi": 34,
          "progress": 0.13621193039391802,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        }
      ]
    },
    {
      "factionId": "sect_012",
      "factionName": "南越国",
      "members": [
        {
          "name": "祭司阿月",
          "rankName": "筑基",
          "role": "outer_disciple",
          "age": 114,
          "maxAge": 203,
          "qi": 304,
          "progress": 0.18659240996512377,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "世子段昭",
          "rankName": "弟子",
          "role": "heir",
          "age": 37,
          "maxAge": 88,
          "qi": 198,
          "progress": 0.19860778439268612,
          "stone": 60,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": "npc_127",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "采药女青萝",
          "rankName": "炼气",
          "role": "outer_disciple",
          "age": 74,
          "maxAge": 119,
          "qi": 136.39999999999998,
          "progress": 0.05672846520621044,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": "npc_121",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "南越王",
          "rankName": "宗师",
          "role": "leader",
          "age": 32,
          "maxAge": 60,
          "qi": 90,
          "progress": 0.10511451213715034,
          "stone": 540,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "老相国",
          "rankName": "谋士",
          "role": "elder",
          "age": 28,
          "maxAge": 81,
          "qi": 90,
          "progress": 0.3514118346919626,
          "stone": 180,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "山民首领",
          "rankName": "弟子",
          "role": "outer_disciple",
          "age": 62,
          "maxAge": 95,
          "qi": 70.4,
          "progress": 0.0873613044707068,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": "npc_025",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "密林巡守",
          "rankName": "弟子",
          "role": "outer_disciple",
          "age": 44,
          "maxAge": 95,
          "qi": 64,
          "progress": 0.036264429422276985,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "溪桥校尉",
          "rankName": "弟子",
          "role": "outer_disciple",
          "age": 39,
          "maxAge": 84,
          "qi": 64,
          "progress": 0.1939153633204561,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "白象卫",
          "rankName": "弟子",
          "role": "outer_disciple",
          "age": 56,
          "maxAge": 85,
          "qi": 64,
          "progress": 0.07186321721009498,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "南岭将军",
          "rankName": "将军",
          "role": "outer_disciple",
          "age": 46,
          "maxAge": 89,
          "qi": 34,
          "progress": 0.1706015227505318,
          "stone": 2,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        }
      ]
    },
    {
      "factionId": "org_auction",
      "factionName": "万宝楼",
      "members": [
        {
          "name": "金万两",
          "rankName": "元婴",
          "role": "leader",
          "age": 807,
          "maxAge": 1370,
          "qi": 1600,
          "progress": 0.2311384099756078,
          "stone": 200,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        }
      ]
    },
    {
      "factionId": "org_escort",
      "factionName": "万里镖行",
      "members": [
        {
          "name": "铁行云",
          "rankName": "金丹",
          "role": "leader",
          "age": 334,
          "maxAge": 594,
          "qi": 1100,
          "progress": 0.26767645856754047,
          "stone": 200,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": "npc_055",
          "childrenCount": 0,
          "alive": true
        }
      ]
    },
    {
      "factionId": "org_assassin",
      "factionName": "天机杀阁",
      "members": [
        {
          "name": "鬼面",
          "rankName": "元婴",
          "role": "leader",
          "age": 594,
          "maxAge": 1032,
          "qi": 1600,
          "progress": 0.049235448298142345,
          "stone": 200,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        }
      ]
    },
    {
      "factionId": "org_bounty",
      "factionName": "悬赏阁",
      "members": [
        {
          "name": "赵信",
          "rankName": "金丹",
          "role": "leader",
          "age": 326,
          "maxAge": 544,
          "qi": 1000,
          "progress": 0.021307529665649992,
          "stone": 200,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        }
      ]
    },
    {
      "factionId": "org_market",
      "factionName": "百灵坊市",
      "members": [
        {
          "name": "柳如烟",
          "rankName": "金丹",
          "role": "leader",
          "age": 405,
          "maxAge": 603,
          "qi": 1000,
          "progress": 0.1818831046450302,
          "stone": 200,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        }
      ]
    },
    {
      "factionId": "org_intelligence",
      "factionName": "妙音阁",
      "members": [
        {
          "name": "月听雨",
          "rankName": "元婴",
          "role": "leader",
          "age": 608,
          "maxAge": 1338,
          "qi": 1600,
          "progress": 0.11741166378066302,
          "stone": 200,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        }
      ]
    },
    {
      "factionId": "__wanderer__",
      "factionName": "散修（无门派）",
      "members": [
        {
          "name": "独孤求",
          "rankName": "元婴",
          "role": "wanderer",
          "age": 681,
          "maxAge": 1209,
          "qi": 1320,
          "progress": 0.12601178509418898,
          "stone": 0,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": "npc_202",
          "childrenCount": 1,
          "alive": true
        },
        {
          "name": "周婆婆",
          "rankName": "金丹",
          "role": "wanderer",
          "age": 265,
          "maxAge": 659,
          "qi": 660,
          "progress": 0.13251215199979752,
          "stone": 0,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": "npc_209",
          "childrenCount": 1,
          "alive": true
        },
        {
          "name": "楚狂",
          "rankName": "金丹",
          "role": "wanderer",
          "age": 400,
          "maxAge": 599,
          "qi": 600,
          "progress": 0.2473987054757181,
          "stone": 0,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "云游子",
          "rankName": "金丹",
          "role": "wanderer",
          "age": 349,
          "maxAge": 534,
          "qi": 600,
          "progress": 0.2214812840231563,
          "stone": 0,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "赤面鬼王",
          "rankName": "筑基",
          "role": "wanderer",
          "age": 150,
          "maxAge": 279,
          "qi": 510,
          "progress": 0.2774422002902074,
          "stone": 0,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": "npc_208",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "红药",
          "rankName": "筑基",
          "role": "wanderer",
          "age": 155,
          "maxAge": 233,
          "qi": 330,
          "progress": 0.06355606025891974,
          "stone": 0,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": "npc_203",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "蛊婆",
          "rankName": "筑基",
          "role": "wanderer",
          "age": 101,
          "maxAge": 204,
          "qi": 330,
          "progress": 0.2151800301499962,
          "stone": 0,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": "npc_215",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "铁手张",
          "rankName": "筑基",
          "role": "wanderer",
          "age": 109,
          "maxAge": 253,
          "qi": 330,
          "progress": 0.22209360805773598,
          "stone": 0,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": "npc_213",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "李剑生",
          "rankName": "筑基",
          "role": "wanderer",
          "age": 115,
          "maxAge": 205,
          "qi": 300,
          "progress": 0.12337560164965401,
          "stone": 0,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "孙不败",
          "rankName": "筑基",
          "role": "wanderer",
          "age": 136,
          "maxAge": 295,
          "qi": 300,
          "progress": 0.2100613362028212,
          "stone": 0,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "秦无涯",
          "rankName": "筑基",
          "role": "wanderer",
          "age": 130,
          "maxAge": 230,
          "qi": 300,
          "progress": 0.24555432258765375,
          "stone": 0,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "陈老三",
          "rankName": "炼气",
          "role": "wanderer",
          "age": 34,
          "maxAge": 105,
          "qi": 132,
          "progress": 0.21405274358867388,
          "stone": 0,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": "npc_204",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "白素素",
          "rankName": "炼气",
          "role": "wanderer",
          "age": 38,
          "maxAge": 102,
          "qi": 132,
          "progress": 0.2526246674662486,
          "stone": 0,
          "contribution": 0,
          "quests": 0,
          "gender": "female",
          "daoCompanionId": "npc_200",
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "陆平",
          "rankName": "炼气",
          "role": "wanderer",
          "age": 71,
          "maxAge": 112,
          "qi": 120,
          "progress": 0.15930197863474968,
          "stone": 0,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "方小鱼",
          "rankName": "炼气",
          "role": "wanderer",
          "age": 73,
          "maxAge": 109,
          "qi": 120,
          "progress": 0.039304028317831335,
          "stone": 0,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "小六子",
          "rankName": "炼气",
          "role": "wanderer",
          "age": 62,
          "maxAge": 104,
          "qi": 120,
          "progress": 0.0711032495492425,
          "stone": 0,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        },
        {
          "name": "刘龙",
          "rankName": "凡人",
          "role": "disciple",
          "age": 0,
          "maxAge": 93,
          "qi": 0,
          "progress": 0,
          "stone": 0,
          "contribution": 0,
          "quests": 0,
          "gender": "male",
          "daoCompanionId": null,
          "childrenCount": 0,
          "alive": true
        }
      ]
    }
  ],
  "breakthroughs": [],
  "deaths": [],
  "companionLog": [
    {
      "day": 60,
      "npc1Id": "npc_031",
      "npc1Name": "沈孤剑",
      "npc2Id": "npc_032",
      "npc2Name": "柳穿云",
      "faction": "sect_002"
    },
    {
      "day": 60,
      "npc1Id": "npc_045",
      "npc1Name": "顾云台",
      "npc2Id": "npc_043",
      "npc2Name": "周怀素",
      "faction": "sect_003"
    },
    {
      "day": 60,
      "npc1Id": "npc_069",
      "npc1Name": "灰尾",
      "npc2Id": "npc_068",
      "npc2Name": "朱砂",
      "faction": "sect_006"
    },
    {
      "day": 60,
      "npc1Id": "npc_070",
      "npc1Name": "丹青子",
      "npc2Id": "npc_071",
      "npc2Name": "白芷长老",
      "faction": "sect_007"
    },
    {
      "day": 60,
      "npc1Id": "npc_083",
      "npc1Name": "青丘长老",
      "npc2Id": "npc_005",
      "npc2Name": "鬼母",
      "faction": "sect_009"
    },
    {
      "day": 60,
      "npc1Id": "npc_103",
      "npc1Name": "蛮骨",
      "npc2Id": "npc_081",
      "npc2Name": "藏星",
      "faction": "sect_010"
    },
    {
      "day": 60,
      "npc1Id": "npc_107",
      "npc1Name": "太师裴玄",
      "npc2Id": "npc_114",
      "npc2Name": "长公主赵绾",
      "faction": "sect_011"
    },
    {
      "day": 60,
      "npc1Id": "npc_111",
      "npc1Name": "禁军统领",
      "npc2Id": "npc_034",
      "npc2Name": "陆惊鸿",
      "faction": "sect_011"
    },
    {
      "day": 60,
      "npc1Id": "npc_120",
      "npc1Name": "东宫侍卫统领",
      "npc2Id": "npc_073",
      "npc2Name": "辛夷",
      "faction": "sect_011"
    },
    {
      "day": 60,
      "npc1Id": "npc_121",
      "npc1Name": "世子段昭",
      "npc2Id": "npc_127",
      "npc2Name": "采药女青萝",
      "faction": "sect_012"
    },
    {
      "day": 60,
      "npc1Id": "npc_128",
      "npc1Name": "山民首领",
      "npc2Id": "npc_025",
      "npc2Name": "秦若水",
      "faction": "sect_012"
    },
    {
      "day": 60,
      "npc1Id": "npc_131",
      "npc1Name": "铁行云",
      "npc2Id": "npc_055",
      "npc2Name": "幽姬",
      "faction": "org_escort"
    },
    {
      "day": 60,
      "npc1Id": "npc_200",
      "npc1Name": "陈老三",
      "npc2Id": "npc_204",
      "npc2Name": "白素素",
      "faction": null
    },
    {
      "day": 60,
      "npc1Id": "npc_203",
      "npc1Name": "赤面鬼王",
      "npc2Id": "npc_208",
      "npc2Name": "红药",
      "faction": null
    },
    {
      "day": 60,
      "npc1Id": "npc_209",
      "npc1Name": "独孤求",
      "npc2Id": "npc_202",
      "npc2Name": "周婆婆",
      "faction": null
    },
    {
      "day": 60,
      "npc1Id": "npc_215",
      "npc1Name": "铁手张",
      "npc2Id": "npc_213",
      "npc2Name": "蛊婆",
      "faction": null
    }
  ],
  "birthLog": [
    {
      "day": 90,
      "childId": "npc_born_1001",
      "childName": "刘龙",
      "childGender": "male",
      "fatherId": "npc_209",
      "fatherName": "独孤求",
      "motherId": "npc_202",
      "motherName": "周婆婆",
      "factionId": null
    }
  ],
  "worldEvents": {
    "modifiers": 0,
    "disasters": 5,
    "attacks": 0,
    "alliances": 8,
    "factionDeaths": 0,
    "companionPairs": 16,
    "totalBirths": 1
  },
  "revengePvp": {
    "huntTriggers": 0,
    "killTriggers": 0,
    "enemySlain": 0,
    "slainByEnemy": 0,
    "wounded": 0,
    "slainDeaths": 0,
    "revengeObsessionsAlive": 0
  },
  "diagnostics": [
    "势力行为单一: \"加强防御\" 占 79.8%",
    "无势力覆灭，缺乏淘汰机制",
    "无 NPC 完成突破，修炼节奏可能偏慢",
    "无 NPC 死亡，寿命系统可能未生效"
  ]
};